# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Build, test, publish aocli

on:
  push:
    tags:
      - 'aocli-v*'

jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: aocli
            asset_name: aocli-linux-amd64
          - os: windows-latest
            artifact_name: aocli.exe
            asset_name: aocli-windows-amd64
          - os: macos-latest
            artifact_name: aocli
            asset_name: aocli-darwin-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Tidy modules
        run: go mod tidy
  
      - name: Test
        run: go test -v ./...

      - name: Build aocli
        run: go build -v ./cmd/aocli
        
      - name: Upload binaries to artifact 
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }} -- $ {{ github.ref }}
          path: ./${{ matrix.artifact_name }}
